### ISSUE TITLE
FR4. Stall Selection/Tracking

### ISSUE THREAD

**Issue by TheOneWhoCodes** [SIU-CS/Biggie_Software-production#5]
The software shall allow for stall tracking. Whether the user is a customer or an administrator, they will have access to which stalls are currently paid for and unavailable and which are available.

Tasks
- [x]  Modify dashboard to show only user's parking spot and associated timer - Zach
- [x]  Add time increments user can select from - Avtar
- [x]  Create a tab for admins to see which spots are paid for - Zach & Avtar
